import {PhoneCall,FileText,CalendarDays,ShieldCheck,Share2,Download,CheckCircle2} from "lucide-react";import {patient} from "../data/mockPatient";import {routines} from "../data/mockRoutines";import {useState} from "react";
export default function CaregiverDashboard(){const [sent,setSent]=useState(false);return <div className="caregiver-page">
 <section className="patient-profile card"><div className="avatar large">👴🏽</div><div className="profile-main"><span className="eyebrow green-text">ASHA Connected</span><h1>Grandfather Biren <small>(82 yrs)</small></h1><p className="coral-text">● Mild Cognitive Impairment (Early Stage)</p><p>● Primary Dr. Ananya B. (Daughter)</p></div><div className="profile-actions"><button className="icon-action">▣<small>View ASHA Data</small></button><button className="icon-action">▤<small>Log Note</small></button><button className="coral-btn" onClick={()=>alert("Emergency call to caregiver team.")}><PhoneCall/> Emergency Call</button></div></section>
 <div className="status-strip"><b>● Status:</b> Resting comfortably at home &nbsp;•&nbsp; All Morning Vitals Normal (Assessed 08:39 AM) <span>↗ Jorhat Residence (Ward 4) &nbsp; ◷ Pending 94%</span></div>
 <section className="care-grid">
  <CognitiveCard/><RoutineProtocol/>
 </section>
 <MoodCard/>
 <section className="bottom-care-grid"><Appointment sent={sent} setSent={setSent}/><Safety/></section>
 </div>}
function CognitiveCard(){return <article className="card metric-card"><span className="eyebrow">LONGITUDINAL METRIC</span><h2>Cognitive Health Index</h2><div className="score-row"><div className="ring"><b>78</b><small>/100</small></div><div><b>→ Stable past 36 days</b><p>Zero clinical decline flagged across last 14 verbal orientation & image recall sessions.</p></div></div><Metric label="Visual Memory (Tea Leaf & Loom Patterns)" value="82%"/><Metric label="Spatial Recognition (Courtyard & House Map)" value="74%"/><Metric label="Voice Latency Response" value="4.2s (Gentle)"/></article>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b><div className="progress"><span style={{width:value.includes("%")?value:"68%"}}/></div></div>}
function RoutineProtocol(){return <article className="card protocol"><div className="card-head"><div><span className="eyebrow">DAILY TRACKER</span><h2>Routine & Care Protocol</h2></div><span className="success-chip">✓ 85% Completed Today</span></div>{["Morning Blood Pressure & Pulse","Warm Water Hydration Target","Afternoon Brahmaputra River Fauna Recall","Evening Donepezil (5mg)"].map((x,i)=><div className="protocol-row" key={x}><span className={"protocol-icon i"+i}>{i===0?"☷":i===1?"◉":i===2?"♧":"□"}</span><div><b>{x}</b><small>{i===0?"Recorded: 124/82 mmHg • Pulse 71 bpm":i===1?"4 of 6 Grass Bottles Logged (1.4L of 2.0L goal)":i===2?"Assisted Brain Game module completed with grandchild":"Scheduled with warm milk"}</small></div><span>{i===1?<button className="mini-add">+ Add 1 Cup</button>:i===3?"Scheduled":<CheckCircle2 className="ok"/>}</span></div>)}</article>}
function MoodCard(){return <section className="card mood-card"><div className="card-head"><div><span className="eyebrow">AFFECTIVE WELLBEING</span><h2>7-Day Emotional Stability & Mood Spectrum</h2></div><div className="legend">● Joyful / Calm &nbsp; ● Confused &nbsp; ● Agitated</div></div><div className="mood-grid">{["Sun|Serene","Mon|Engaged","Tue|Mild Fog","Wed|Vibrant","Thu|Restless","Fri|Peaceful","Today|Joyful"].map((x,i)=>{let [a,b]=x.split("|");return <div className={"mood-day "+(i===6?"today":"")} key={a}><small>{a}</small><span>{["☻","☺","◌","☻","◒","☺","☻"][i]}</span><b>{b}</b><em>{i===6?"Active speech":"Voice check"}</em></div>})}</div><div className="observation"><b>✦ Asha Cognitive Pattern Observation:</b><span>Positive emotional engagement spikes reliably during afternoon tea-garden pattern games and scheduled voice calls with his granddaughter in Guwahati. Sundowning restlessness is minimized when porch lighting is activated by 5:15 PM.</span><button onClick={()=>navigator.clipboard?.writeText("Asha Cognitive Pattern Observation") }><Share2/> Share with Care Team</button></div></section>}
function Appointment({sent,setSent}){return <article className="card appointment"><span className="eyebrow">CLINICAL APPOINTMENT</span><span className="count-chip coral-count">In 4 Days</span><h2>Specialist Consultation</h2><div className="doctor-row"><div className="doctor-icon">▣</div><div><b>Dr. H. K. Sarma, MD (Neurology)</b><small>Gauhati Medical College & Hospital (GMCH)<br/>Sept 12, 2024 • 11:30 AM<br/>Hybrid (Video Tele-Clinic or In-person)</small></div></div><div className="appointment-actions"><button className="dark-btn" onClick={()=>alert("Clinical report prepared for export.")}><Download/> Export Clinical PDF (ICD-10)</button><button className="light-btn" onClick={()=>setSent(true)}><Share2/> {sent?"Sent to Bina":"Share Access with Bina (ASHA)"}</button></div></article>}
function Safety(){return <article className="card safety"><span className="eyebrow">DEFENSIVE CARE TELEMETRY</span><h2>Safety Thresholds</h2><div className="safety-box"><span>DRIVE_FILE_</span><b>Geo-fence Active</b><small>Jorhat Family Compound (360m)</small><CheckCircle2/></div><div className="safety-row">⚠ Missed Dose Alert <small>Notify Daughter & ASHA after +45 min</small><span>✓</span></div><div className="safety-row">▣ Encrypted NDHM Health ID Linked <small>Configure Limits</small></div></article>}
